# Generated by Django 4.1 on 2022-11-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.sex'),
        ),
    ]
