# Generated by Django 4.1 on 2022-11-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_doctor_name_remove_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/scan/'),
        ),
    ]
