# Generated by Django 4.1 on 2022-11-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_patient_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(default=1234567890, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.bloodgroup'),
        ),
    ]
