# Generated by Django 4.1.3 on 2022-11-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_scan_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='profile_pic',
            new_name='img',
        ),
    ]
